INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (180,'naif','lagu wanita'),
	 (4604,'unknown','modus'),
	 (395,'la luna','bulan'),
	 (11783,'gangga','dreamin of you'),
	 (4644,'ruth sahanaya','jangan semudah ini'),
	 (11885,'unknown','emang kenape'),
	 (17174,'unknown','life'),
	 (14145,'alena wu','怀念家乡 (miss my hometown)'),
	 (17516,'unknown','never in you'),
	 (13922,'unknown','disini');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (17965,'unknown','in a fiya'),
	 (16554,'andy histori','bersamamu aku senang'),
	 (5756,'unknown','wahai orang beriman'),
	 (17936,'gangstarasta','seminggu'),
	 (7641,'oneway','seribu tahun lagi'),
	 (2847,'unknown','tamasya sendiri'),
	 (12813,'exotheband feat dekka mayo , kenatha','menunggu apalagi'),
	 (16604,'deabdil','bumi, bulan, matahari'),
	 (8534,'unknown','substansi'),
	 (10011,'bowo','sempurna untuk ku');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (859,'unknown','sikat boti awas mati'),
	 (4131,'unknown','semu'),
	 (4580,'damon koeswoyo','ampuni aku'),
	 (15287,'unknown','waktu yang paling tepat'),
	 (14989,'unknown','jaga hati'),
	 (17615,'unknown','pertemuan, perpisahan, harapan'),
	 (10825,'dzee, candra kim','dinda kecil'),
	 (15075,'unknown','a love letter'),
	 (12769,'unknown','ku setia padamu'),
	 (4815,'unknown','tanpamu');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (10673,'bilal indrajaya','purnama'),
	 (17287,'atlesta','dont need love'),
	 (17855,'souljah','bilang i love you'),
	 (3380,'kidnap katrina','diam (jangan bersuara)'),
	 (5816,'unknown','b.d.i'),
	 (7683,'bobby febian','mulia'),
	 (654,'anang dan krisdayanti','sudahi marahmu'),
	 (17150,'alex kuple','in your head'),
	 (7159,'alena wu','here with me'),
	 (13066,'unknown','jangan kembali');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9970,'unknown','tuhan kembalikan dia'),
	 (8887,'good ol dreams','tentang lagu'),
	 (7825,'unknown','brushdtrokes esemble'),
	 (6543,'koes plus','perasaan cintaku'),
	 (4722,'unknown','tragedi tragis 1989'),
	 (16497,'igoy jangkung','hoyong kasalira'),
	 (15112,'hi.jo','beda bahagia'),
	 (11145,'unknown','sahabatku'),
	 (17926,'goldface','putus'),
	 (4729,'willy anggawinata & brigitta tifanny','cerita kita');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (16605,'unknown','satu-satunya'),
	 (5711,'bimbo','kita adalah satu'),
	 (13322,'abiem pangestu feat esa risty','nandur loro'),
	 (8973,'unknown','starting over'),
	 (13119,'ari amnan','lost in the black hole'),
	 (15645,'arnando putra, chiemi yoshida, junna adachi','i thought it was clear'),
	 (3333,'vopstfm','ceritaku'),
	 (2605,'saykoji & sheryl','line today news'),
	 (7250,'unknown','debbie & ratih: karier, cinta & timbangan'),
	 (17580,'gerap gurita','berdiri');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (8581,'unknown','unreachable'),
	 (11562,'unknown','aku punya burung'),
	 (17026,'coki & the blur ambience','bara cinta'),
	 (17871,'unknown','hanya ingin pulang'),
	 (10847,'patria nk','belanda masih jauh'),
	 (728,'sarah azhari','semestinya'),
	 (4192,'skinnyfabs','circus'),
	 (14187,'unknown','i am yours'),
	 (4956,'unknown','mata-mata harimu'),
	 (10279,'unknown','ini kenalan lo kan');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (11447,'unknown','pilihan hatimu'),
	 (6680,'unknown','chanteplereu'),
	 (11303,'unknown','kemamaliran'),
	 (6514,'koes plus','luka'),
	 (6388,'unknown','satu malam'),
	 (10321,'frandy, besta bloom','indonesiaku'),
	 (9287,'la hila','sendiri dulu'),
	 (17222,'angest','uang kuliah tinggi'),
	 (3423,'unknown','high'),
	 (1725,'unknown','katakan');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9896,'galyas','akulah yang mencintaimu'),
	 (17710,'unknown','kembang ilalang'),
	 (3459,'cinta harici','ampuni aku'),
	 (15281,'noin bullet','heart beat slow'),
	 (8893,'unknown','jangan sampai lelah'),
	 (14929,'jesus inside music','kupercaya salibmu'),
	 (14563,'unknown','pygc'),
	 (5611,'unknown','napak tilas'),
	 (8347,'bagus ananda','untuk indonesia'),
	 (2912,'unknown','h u & d');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9352,'unknown','aku suka sayur'),
	 (16951,'faye risakotta','the way to go'),
	 (2378,'koes plus','du du du'),
	 (18535,'the skibers','the third coming'),
	 (1398,'ungu','doa'),
	 (18136,'baim','bersamamu'),
	 (18174,'hindia','perkara tubuh'),
	 (682,'krisdayanti','jangan usai'),
	 (5876,'unknown','adakah senyummu untukku'),
	 (6433,'koes plus','bernyanyi sambil menari');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (12493,'unknown','let me (feat. rifka rachman)'),
	 (17320,'unknown','essential love'),
	 (11120,'unknown','something something insane'),
	 (2256,'koes plus','hatiku hatimu'),
	 (15117,'unknown','abang sayang'),
	 (15288,'kojek','tahan napsu'),
	 (13312,'dian agustin','ramadhan syahru syiam'),
	 (4739,'olly oxen','jauhari'),
	 (10549,'unknown','ghost town'),
	 (14072,'aziz dhanu','hasrat diri');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9194,'mika rafello','ketika aku di ketika'),
	 (10285,'unknown','kalau terowongan ini'),
	 (9330,'unknown','java chinese'),
	 (8869,'tri suaka','bisakah tanpamu'),
	 (8538,'calista amadea','butterfly'),
	 (15427,'doddie, tongkie','please'),
	 (4194,'unknown','cintai dengan abadi'),
	 (7945,'pakdhe baz','sesisih moto'),
	 (1663,'naff','terendap laraku'),
	 (4758,'fyn','quantum cinta');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (3922,'unknown','mata ketiga cinta'),
	 (3448,'kenny feat sara fajira','you know'),
	 (10144,'delon, irene rejoice','indah pada waktunya (feat. irene rejoice)'),
	 (14265,'unknown','perjuangan terakhir'),
	 (3905,'andre harihandoyo','the boy in love'),
	 (11650,'dipareynardi','relax'),
	 (5901,'djaka bimbo','mass media'),
	 (4360,'teddy adhitya','all of em'),
	 (8270,'unknown','jula juli suraboyo'),
	 (1500,'flanella','anjelie');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (6876,'didi kempot','yuni yuni'),
	 (12517,'ari pramundito','karenamu'),
	 (12405,'ape on the roof','rise'),
	 (14137,'the brandals','100 km/jam'),
	 (17112,'delisha okta','apa bisa'),
	 (2232,'unknown','larut senja'),
	 (8871,'angga candra','tunggu sejenak'),
	 (12795,'alex kuple','silence'),
	 (18351,'destroy you (again)','naykilla'),
	 (15393,'unknown','thank you');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (16541,'unknown','hanya yesus tuhan'),
	 (17042,'unknown','pujilah yahweh'),
	 (1470,'unknown','sejauh apapun'),
	 (2668,'unknown','insomnia'),
	 (10340,'rida rsd','harmoni alam'),
	 (8425,'ify alyssa','what about us?'),
	 (13926,'unknown','teras & angin malam'),
	 (10656,'nathania wibowo','tanpa banyak bicara'),
	 (8218,'koes plus','pak tani'),
	 (9647,'unknown','awal');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (10665,'sexy goath, bonie mc','sa ae lau'),
	 (9995,'mkartikawati','happy birthday'),
	 (17418,'aribowoid, nita reviana','lungo ninggal cerito'),
	 (47,'samsons','selamat tinggal'),
	 (17388,'daniel rumbekwan','doa'),
	 (783,'unknown','suara'),
	 (6515,'koes plus','maafkan aku'),
	 (2490,'koes plus','jumpa 123'),
	 (1859,'the rain','dengar bisikku'),
	 (1671,'naff','nelangsa');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (12347,'unknown','takkan berpaling'),
	 (10431,'no koes','sang surya'),
	 (13673,'unknown','tatu jeru'),
	 (5968,'pandeglang various artist','wayahna lur'),
	 (17723,'natasha','matahari'),
	 (18006,'unknown','bukan surga harapanku'),
	 (18199,'bungen','melankoli kota'),
	 (5443,'unknown','makna cinta'),
	 (9135,'unknown','before you'),
	 (13663,'jaka rohmana','terketuk cinta');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (4157,'ezzar','kita (sekedar pesan)'),
	 (18395,'figura renata','tangan kecil'),
	 (3985,'near feat nino minggo, yenny kabupung','salahkah berbeda'),
	 (3991,'gamma1','cinta pertama'),
	 (877,'andien','metamorfosa'),
	 (16920,'unknown','jangan tinggalkan'),
	 (443,'la luna','cemburu'),
	 (10133,'numata','terlalu cinta'),
	 (17001,'unknown','blessing in disguise'),
	 (16985,'unknown','sio nona');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (3373,'kidnap katrina','muak'),
	 (14975,'unknown','aku tresno kowe'),
	 (12497,'gruvi','masih mencintaimu'),
	 (3401,'unknown','pencinta ulung'),
	 (8602,'unknown','easily'),
	 (11335,'unknown','tunduina lan kemapparisan'),
	 (12806,'unknown','into the light'),
	 (16768,'victor pradipta','lament.'),
	 (4390,'unknown','sudah biasa'),
	 (4612,'unknown','rindu masa kecil');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (505,'the adams','pesona persona'),
	 (4804,'the45','hati yang lain'),
	 (18010,'zerosix park','karma'),
	 (11255,'unknown','apara kasalanku'),
	 (5054,'unknown','kesengsem'),
	 (16749,'unknown','dewi cinta'),
	 (13267,'mr jarwo','ujang dkk'),
	 (7051,'muslih','ukhuwah acapella'),
	 (8413,'otta tarrega','amber'),
	 (18322,'unknown','hati untukmu mati');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (17814,'nowela mikhelia','runnin'),
	 (2892,'junior soemantri','ribuan saya'),
	 (6668,'arsha composer','istimewa'),
	 (1875,'unknown','lagu untuk persahabatan'),
	 (9991,'unknown','hujan'),
	 (5626,'fiersa besari','epilog'),
	 (9426,'rida,sita,dewi','tak perlu memiliki'),
	 (3461,'take over x jhon paul ivan','sudahi saja'),
	 (3547,'pongki barata','rahasia'),
	 (13638,'unknown','stasiun purwosari');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (2495,'koes plus','mari-mari'),
	 (412,'la luna','tetap setia'),
	 (16803,'raben','real talk'),
	 (11389,'ishak rante toding','rasa di hatiku'),
	 (3368,'unknown','im only good at first dates'),
	 (18048,'perfecta','no more'),
	 (7285,'judika','hilang tapi ada'),
	 (6309,'didi kempot','plong'),
	 (10446,'chicha koeswoyo','adikku manis'),
	 (17365,'the rentenir','on your birthday');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (6934,'dita','lagu rindu'),
	 (13751,'unknown','dari hati'),
	 (10234,'madaharsa','tak lagi sama'),
	 (14959,'the great harvest','kau'),
	 (9744,'unknown','ingin lupa'),
	 (9458,'priadhs feat nasya','candywine'),
	 (1749,'unknown','hatiku pilu'),
	 (17370,'unknown','tidak ada salju disini pt 5'),
	 (3384,'unknown','siklus'),
	 (5116,'ran','karena kusuka dirimu');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (12398,'unknown','pengkhianat wanita'),
	 (7721,'unknown','powerful name'),
	 (14601,'monica christiana','malam tak berjudul'),
	 (12308,'unknown','samalona'),
	 (5686,'sam bimbo','dia'),
	 (11578,'unknown','cinta cinta cinta'),
	 (7660,'bobby febian','kunikmati kebaikanmu'),
	 (11205,'gangga','empty house'),
	 (4776,'dul jaelani','sang pemuja'),
	 (2032,'unknown','malam resah');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (16546,'stve jay','hbd mom'),
	 (10427,'no koes','jaranan'),
	 (5379,'unknown','the blessed sigh'),
	 (17201,'jason ranti','sekilas info'),
	 (13985,'brockers','kuingin'),
	 (4370,'unknown','just you'),
	 (16238,'unknown','verset ii'),
	 (10024,'unknown','rembik'),
	 (6077,'gaols naibaho','lupahon ma hallet mi'),
	 (9456,'unknown','redemption');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9747,'qodir','penyihir'),
	 (11413,'salma margareth','torro mo diingaran'),
	 (477,'the adams','fool'),
	 (6900,'edo martin','sekopi'),
	 (8979,'unknown','baginda muhammad'),
	 (7258,'unknown','kangen - piano version'),
	 (607,'anang dan krisdayanti','sinari'),
	 (7610,'unknown','blank way'),
	 (18057,'priadhs feat maro','gaslight'),
	 (17466,'unknown','memori');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (17117,'malik','distance'),
	 (16237,'unknown','falling out of rhyme'),
	 (7453,'indragersn','rollin'),
	 (12753,'unknown','story of my life'),
	 (17640,'unknown','loveless'),
	 (4201,'la hila','kupu kupu biru'),
	 (6577,'koes plus','takdir kehidupanku'),
	 (1455,'unknown','tak seindah malam kemarin'),
	 (14548,'unknown','rayuan'),
	 (10814,'el alice','ku rindu ibu');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (15233,'benyamin s feat. eddy sud','siti marsitol'),
	 (15268,'unknown','one day at a time'),
	 (15208,'unknown','penganten'),
	 (3153,'mondo gascaro','awkward'),
	 (6675,'amsb family','selalu bersyukur dong'),
	 (18004,'pugar restu julian','selamat tinggal'),
	 (13115,'unknown','ente kadang kadang'),
	 (3668,'narha anindyaguna','a mothers love in c minor'),
	 (18162,'rub of rub','ubah warnaku menjadi kuning dari biru yang membelenggu'),
	 (3490,'jikustik','separuh hati');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (18381,'figura renata','sebuah anomali'),
	 (14690,'unknown','abadi'),
	 (10071,'axl hunila','cuma butuh itu'),
	 (9620,'unknown','hey bitch'),
	 (9091,'unknown','27'),
	 (8207,'unknown','verlangen'),
	 (5469,'unknown','ego'),
	 (11426,'unknown','keinginanku'),
	 (11158,'unknown','sukacita melimpah'),
	 (9964,'ifa fachir, dimas wibisana','selesai');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (3566,'kahitna','fly me over'),
	 (1754,'unknown','my love'),
	 (814,'raisa','tentang cinta'),
	 (9052,'heri yoselin','cowok sejati'),
	 (12843,'unknown','hujan di langit'),
	 (18326,'unknown','sambutlah hari ini'),
	 (12649,'unknown','sunny day and smiles'),
	 (3662,'unknown','singgah'),
	 (16900,'unknown','new hope'),
	 (775,'christie kaori','aku selalu ada');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (2043,'koes bersaudara','pager kuning'),
	 (10423,'unknown','seindah dulu'),
	 (4699,'diskoria feat dian sastro','serenata jiwa lara'),
	 (10221,'unknown','uncertainty'),
	 (12144,'nathania wibowo','better'),
	 (10353,'unknown','selamat jalan sahabatku'),
	 (10611,'alexa','satu kosong'),
	 (6438,'koes plus','bunga'),
	 (10416,'no koes','buah jambu'),
	 (9309,'unknown','hanya untukmu');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (13503,'unknown','pelarian'),
	 (15614,'unknown','kucari bayangmu'),
	 (15547,'mala agatha','update status'),
	 (14153,'unknown','cinta menepi'),
	 (17783,'unknown','soap in my eye'),
	 (10623,'alexa','cinta melulu'),
	 (754,'unknown','labirin epidemi'),
	 (2266,'koes plus','aku dan dia'),
	 (2585,'anti heroes','glowing'),
	 (9925,'willy anggawinata','mimpi indahku');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (12554,'unknown','sepenuhnya'),
	 (9321,'lightcraft','dream dancer'),
	 (8957,'agus wisman','sheila'),
	 (9780,'unknown','engkaulah hidupku'),
	 (16618,'paul partohap, deabdil, remi, amira karin','rayakan hari ini'),
	 (14194,'the brandals','anjing urban (sang korban ii)'),
	 (15593,'unknown','cinta tak selalu bersama'),
	 (7038,'unknown','apa yang terjadi'),
	 (17576,'unknown','peduli'),
	 (17745,'kita-kita','sahabatku bintang');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (11008,'unknown','erwin minta cuti'),
	 (3067,'unknown','bilang sa rindu'),
	 (18084,'the chronicles of happiness ride and services','pilih aku atau dia'),
	 (16509,'unknown','let the music on'),
	 (14573,'unknown','kabut'),
	 (13185,'unknown','() battesimo'),
	 (13447,'erna arisma','buang mantan'),
	 (16806,'unknown','polaritas mediokritas'),
	 (15616,'unknown','tuhan tolonglah'),
	 (17421,'unknown','manut dalane gusti');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (3911,'arah','i want to rock n roll'),
	 (2515,'unknown','aku pergi'),
	 (17983,'abel huray','youre always the best'),
	 (9113,'unknown','everything i do'),
	 (9827,'und bodevan','whyyouneedspaceifyoudont?'),
	 (12794,'alex kuple','sad stories'),
	 (5679,'unknown','cinta suci seorang perawan'),
	 (538,'unknown','meninggalkanmu'),
	 (9497,'unknown','ggs ganteng-ganteng swag'),
	 (5476,'rara','panggung gemilang');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (14539,'saras','jomlo happy'),
	 (4753,'unknown','asmara'),
	 (8233,'unknown','mobil tua'),
	 (10683,'unknown','cerita yuli'),
	 (17100,'karan aujla','mexico'),
	 (12490,'unknown','harapanku'),
	 (13563,'unknown','bancar buncur'),
	 (7004,'unknown','mengharapmu'),
	 (1616,'naff','bila aku pulang'),
	 (5179,'unknown','cinta kapan datang');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (10770,'adi darmawan','etude 5'),
	 (6966,'unknown','syair ilahi'),
	 (5957,'addictive','wujudkan'),
	 (9812,'lokus','perubahan tak butuh rating'),
	 (83,'unknown','fett sang pemburu'),
	 (13015,'unknown','absolute'),
	 (14831,'mima','come over'),
	 (12319,'unknown','puncak jatuh cinta'),
	 (1971,'lesti','ada cerita'),
	 (16235,'unknown','tongue-tied');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (7842,'unknown','blood trap'),
	 (5754,'bimbo','titian serambut dibelah tujuh'),
	 (16907,'unknown','semesta merestui'),
	 (1726,'po3three','ku tak laku laku'),
	 (9123,'svmmerdose','more than friends'),
	 (11161,'ndc worship','tak terbatas'),
	 (16519,'kapten piping','bubur ayam'),
	 (5732,'bimbo','rasul hancurkan berhala'),
	 (12868,'unknown','dan hujan 1'),
	 (11401,'unknown','senga mo tu kadammu');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (1206,'nadya fatira','biasa-biasa saja'),
	 (2916,'unknown','heaven in hell'),
	 (659,'anang','separuh jiwaku pergi'),
	 (2104,'unknown','pada siapa'),
	 (5924,'sam, djaka, iin','tahun 2000'),
	 (18046,'unknown','berasa muda'),
	 (2062,'koes bersaudara','wit gedhang'),
	 (4864,'unknown','sorak sorai'),
	 (18241,'unknown','anxiety teman anak ahensi'),
	 (2930,'bayu risa','better');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (1645,'unknown','bumiku bumimu'),
	 (1925,'unknown','aku menyesal'),
	 (11193,'redo daeng badjie','cahaya'),
	 (10122,'unknown','ingatkah diriku'),
	 (14785,'jis ministry','lebih mengasihimu'),
	 (4549,'unknown','maafkan'),
	 (9985,'near, mkartikawati','nanti'),
	 (88,'unknown','program party seringai'),
	 (2676,'unknown','tubuhmu membiru tragis'),
	 (1011,'unknown','berkilau');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (14502,'hujan esok hari','circle'),
	 (11965,'unknown','kita dewasa'),
	 (16949,'momonon','we are brother'),
	 (11297,'unknown','dilandi omo kadadianna'),
	 (9318,'sasya arkhisna','tatanan ati'),
	 (2208,'koes plus','adik pandai berjalan'),
	 (6610,'didi kempot','nganti kuru'),
	 (7931,'unknown','air trails (chill version)'),
	 (12294,'unknown','aku memanggil'),
	 (13460,'justy aldrin & rina sainyakit','dua raja satu hati');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (18541,'the skibers','laurie webb'),
	 (16599,'unknown','spasi'),
	 (16327,'ada band','jalan hidupku'),
	 (11100,'unknown','tetaplah terlelap'),
	 (4945,'lotus from jakarta','secret invasion'),
	 (7348,'unknown','viva rrq'),
	 (15138,'unknown','bini tua'),
	 (14734,'unknown','komodo sunset'),
	 (4901,'happy asmara, ray sharir','rasa yang salah'),
	 (6901,'unknown','kursang');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (918,'arsha composer','selamat berbahagia dengannya'),
	 (3087,'maizura','aku tanpamu'),
	 (13656,'unknown','eman tenan'),
	 (10036,'cya','jbaml (jangan buat aku menunggu lama)'),
	 (5156,'unknown','masih bisa panjang'),
	 (3283,'unknown','mr. nice guy'),
	 (3177,'unknown','saat duniaku tenggelam'),
	 (2630,'unknown','i dont know what it is'),
	 (6150,'unknown','dalan anyar'),
	 (846,'unknown','nonton bokep');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (10628,'bibus','bila tiba satu waktu'),
	 (8714,'renny djayoesman','orang masa depan'),
	 (16536,'stve jay','terimalah aku (instrumental)'),
	 (7156,'unknown','terimalah maafku'),
	 (1509,'flanella','tiga hari yang lalu'),
	 (3796,'unknown','pangeran senja,pelindung hutan'),
	 (14852,'unknown','lambai'),
	 (1352,'unknown','aku bukan pilihan hatimu'),
	 (11435,'unknown','pura-pura bahagia'),
	 (772,'anima','ajari aku');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (11684,'the hermansyah','doa'),
	 (5618,'unknown','bandung'),
	 (2569,'unknown','do you love me?'),
	 (16305,'pt menggelora','7 purnama'),
	 (15335,'unknown','dengan semarak majulah'),
	 (9386,'unknown','kelaparan sebelum tidur'),
	 (16500,'ansurya','ribuan senja'),
	 (2614,'unknown','problem is you'),
	 (3746,'fourtwnty','argumentasi dimensi'),
	 (9031,'unknown','ratu youtube');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9953,'unknown','pagi hari'),
	 (18305,'garby band','selamat tinggal'),
	 (17565,'diandras','fenomena romansa'),
	 (602,'unknown','hanya tuhan'),
	 (3672,'narha anindyaguna','wake up'),
	 (17040,'unknown','modus operandi'),
	 (2052,'koes bersaudara','minggu malam'),
	 (14434,'unknown','lebih baik (remastered)'),
	 (9074,'unknown','takut'),
	 (2525,'unknown','no fruits for today');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (13834,'chaseiro','seandainya sederhana'),
	 (18196,'unknown','di bawah lampu'),
	 (10139,'audy','pergi cinta'),
	 (3764,'asteriska','distance'),
	 (2459,'koes plus','mari bernyanyi'),
	 (17655,'havinhell','wake me up'),
	 (978,'unknown','bicara'),
	 (2980,'maria simorangkir','yakin bahagia'),
	 (11577,'unknown','isim dhomir'),
	 (6714,'unknown','sembuhkan jenuh');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (10882,'unknown','selamat pagi'),
	 (18055,'unknown','iki piye'),
	 (11520,'unknown','alif (sastro gending)'),
	 (3209,'diditsaad','surat kaleng'),
	 (4646,'ruth sahanaya','coba lagi'),
	 (2205,'koes plus','padang luas'),
	 (13846,'karimata, lydia nursaid, dian p p','rintangan'),
	 (2228,'unknown','datanglah'),
	 (16295,'unknown','dekapmu'),
	 (10788,'unknown','let the music');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (12580,'unknown','lucky man'),
	 (1948,'unknown','tak bisa bersama'),
	 (4821,'diksoria','balada insan muda'),
	 (1710,'unknown','city lights'),
	 (16233,'neonomora','heartless'),
	 (15389,'unknown','yesus kemenanganku'),
	 (15653,'aufa','other times'),
	 (6907,'unknown','getun'),
	 (17465,'connect worship, bobby febian','kau layak'),
	 (10865,'unknown','jhung kejhungan 1');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (11606,'unknown','only you'),
	 (2719,'yolanda theodora','mr. right'),
	 (17420,'aribowoid, gorat.id','malioboro ninggal cerito'),
	 (6605,'unknown','seperti dulu'),
	 (994,'jemima','pipe tomahawk'),
	 (10360,'rizka zahra tamira','maju fri, majulah negeri'),
	 (12170,'tcash','siana'),
	 (18323,'rcka','kata tetangga'),
	 (4634,'unknown','masa kecil'),
	 (13809,'8 ball','bertahan hidup');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (279,'unknown','be free'),
	 (18185,'unknown','the guiding lights'),
	 (13376,'unknown','rindu mama'),
	 (2197,'koes plus','kemana'),
	 (16292,'unknown','terbuai asmara'),
	 (13750,'unknown','mmm pengen'),
	 (29,'unknown','bahasa cinta'),
	 (17708,'unknown','kehatimu selamanya'),
	 (11638,'unknown','idk how to fall'),
	 (2457,'koes plus','tari selendang');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (14238,'abel huray','main theme from 13 bom di jakarta'),
	 (6622,'strangers','tangisan ibu pertiwi'),
	 (9400,'hindia','tidak ada salju di sini pt 4'),
	 (14892,'mikha tambayong','ini indonesia'),
	 (18020,'unknown','panggil aku sayang'),
	 (14691,'glenn fredly','tanda mata'),
	 (735,'unknown','dusta'),
	 (1666,'naff','dia kekasihku'),
	 (11479,'unknown','puja pau sen ta ti / pau sen ta ti sung ke'),
	 (14513,'unknown','tujuh belas juni');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (6285,'unknown','lingso trisno'),
	 (8680,'unknown','gadis bergelang emas'),
	 (13645,'unknown','ora nitik'),
	 (12035,'unknown','ganjar di hati'),
	 (1643,'unknown','a.n.g'),
	 (2806,'unknown','madjang'),
	 (13719,'8 ball','warteg (warga tegar)'),
	 (11322,'daniel tandirogang','samari puang'),
	 (2199,'koes plus','sendiri dan rahasia'),
	 (1466,'unknown','bidadari jiwa');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (8228,'unknown','jangan kau siksa'),
	 (15392,'unknown','janjiku'),
	 (2420,'unknown','rasa sedih tiada arti'),
	 (1672,'unknown','sekali lagi (melati)'),
	 (3915,'unknown','the land of majene'),
	 (9053,'unknown','bernapas denganku'),
	 (6119,'unknown','by the book'),
	 (13172,'alsa, chris andrian yang','inevitable'),
	 (2410,'unknown','senang-senang bergembira'),
	 (13793,'8 ball','dites votre amour');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (9102,'unknown','bintang yang bersinar'),
	 (8712,'january christy','kereta'),
	 (8975,'unknown','one last dance'),
	 (2730,'unknown','akhir waktu'),
	 (11112,'diosdu','where is your heart'),
	 (3001,'unknown','diam tak bicara'),
	 (8984,'didit saad','honestly i dont'),
	 (763,'unknown','generasiku'),
	 (14038,'soegi bornean','asmalibrasi'),
	 (3329,'unknown','kpk (kembalilah pada kekasihmu)');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (13761,'8 ball','sensual imitasi'),
	 (2962,'unknown','bright as the sun'),
	 (8723,'unknown','buatku kau terbaik'),
	 (13979,'unknown','lawan penjahat korupsi'),
	 (18340,'henkie sahurilla','kasihnya'),
	 (14812,'ainan tasneem','setengah hati'),
	 (2206,'unknown','lompat katak'),
	 (17081,'unknown','jyada jachdi'),
	 (697,'unknown','mengenangmu'),
	 (5670,'unknown','buku harian seorang gadis');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (17500,'closure','coldroom'),
	 (17058,'unknown','bangsaku indonesia'),
	 (6204,'unknown','lindu'),
	 (4681,'unknown','bersama'),
	 (12156,'rizky febian','berona'),
	 (15087,'dhira band','untuk apa'),
	 (14733,'unknown','gego lau le'),
	 (146,'naif','bunga hati'),
	 (11241,'october rain','pelesiran'),
	 (15514,'pop up','boring');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (5826,'unknown','kucari teman'),
	 (6528,'unknown','mentari'),
	 (14355,'chai','radar'),
	 (1821,'st12','putri iklan'),
	 (17857,'bigwave','bohong'),
	 (13789,'8 ball','jangan ragu'),
	 (17998,'unknown','avas breakdown'),
	 (5085,'barasuara','api dan lentera'),
	 (10502,'unknown','saudara tua'),
	 (1959,'unknown','#jangandianggapremeh');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (13996,'unknown','kill your stylist'),
	 (16804,'raben','seperti hutan'),
	 (4710,'unknown','love jokes'),
	 (17008,'unknown','kau yang hilang'),
	 (6491,'koes plus','kan ku songsong hari esok'),
	 (16708,'unknown','3 kata ajaib'),
	 (18146,'the chronicles of happiness ride and services','aku baik-baik saja'),
	 (10523,'unknown','tarawih'),
	 (14522,'indra7','⁠serotonin 6 am'),
	 (17303,'unknown','pesona');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (2758,'hivi!','apa adanya'),
	 (17622,'unknown','seperti nama hari, lagu berpotensi abadi'),
	 (13630,'unknown','hati so lelah'),
	 (1601,'unknown','bila kau pergi nanti'),
	 (13598,'unknown','klangenanku'),
	 (3094,'unknown','tattooed love'),
	 (3775,'asteriska','you'),
	 (16266,'unknown','you look so beautiful'),
	 (15406,'unknown','gandong'),
	 (932,'unknown','temptation');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (17181,'unknown','nina bobo'),
	 (7552,'unknown','pelangi semu'),
	 (14949,'unknown','overthinking'),
	 (10794,'nada tao','batu giok perlu diasah / yi pu cuok pu jen ji'),
	 (3827,'andrea miranda feat teza sumendra','sama'),
	 (10025,'unknown','sorop e sereng'),
	 (4607,'momonon','teh dingin'),
	 (4004,'kelompok penerbang roket','ekspedisi 69'),
	 (1260,'unknown','tuhan tidak tidur'),
	 (10401,'unknown','terang kembali');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (7290,'unknown','c.h.r.i.s.y.e'),
	 (11525,'damar murup','roso pangroso ( sinom sastro gendhing )'),
	 (1525,'unknown','habis 1+1'),
	 (12430,'unknown','have you try?'),
	 (18332,'brigita tan','mati rasa'),
	 (15628,'unknown','tentang kamu'),
	 (14385,'unknown','tanpa hadirmu'),
	 (11493,'nada tao','nyanyian kwan kong / kwan sen miau ce ke'),
	 (900,'risin black hole','dont wanna lose you'),
	 (5354,'rendy pandugo','paper heart');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (1181,'unknown','terluka'),
	 (3211,'diditsaad','malam minggu di taman'),
	 (11695,'gunawan lida','bintang tertutup awan'),
	 (11822,'unknown','singapore'),
	 (9193,'mika rafello','lockdown syndrome'),
	 (13222,'monkey to millionaire','hujan'),
	 (37,'samsons','di ujung jalan'),
	 (3263,'unknown','tirani'),
	 (18374,'figura renata','elegi'),
	 (7,'unknown','akhir rasa ini');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (14390,'unknown','katanya merdeka'),
	 (13605,'unknown','kudu rumasa'),
	 (2679,'efek rumah kaca','lagu kesepian'),
	 (1502,'flanella','bulan'),
	 (12541,'cynatic','fly'),
	 (17553,'unknown','bunga'),
	 (9899,'mr.kitty','after dark'),
	 (13354,'toton caribo ft. gervldo19xx','name up'),
	 (3237,'chrisye','suatu persembahan cinta'),
	 (14861,'junno','gelisah');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (16738,'unknown','semarang kali mantan'),
	 (6106,'indragersn','close my eyes'),
	 (14110,'unknown','sebelum terlanjur'),
	 (4095,'nina','pada saatnya nanti'),
	 (2923,'unknown','bersinar untukku'),
	 (4532,'unknown','rindu'),
	 (4943,'unknown','buryale'),
	 (2905,'7 kurcaci','berakhir dengan senyuman'),
	 (12760,'careless 061','hidup'),
	 (8,'samsons','kenangan terindah');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (8012,'unknown','bangkai'),
	 (16425,'unknown','kalian semua pembunuh'),
	 (11350,'ishak rante toding','danke par ale'),
	 (1605,'naff','dosa apa'),
	 (7806,'hoala & koala','di rumah saja'),
	 (6720,'tami aulia','tetaplah di sini'),
	 (3847,'unknown','mama papa happy'),
	 (11883,'unknown','cape dech'),
	 (11532,'syubbanul muslimin','yo ca kancah sholawat busyro'),
	 (3868,'unknown','i sailed across the sea');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (5013,'pakdhe baz / dhe baz','tak sanding sliramu'),
	 (4746,'ridwan','cinta apa adanya'),
	 (314,'unknown','surrender'),
	 (12861,'gardika gigih pradipta','penantian'),
	 (13527,'unknown','kertas putih'),
	 (10999,'man','ina'),
	 (4664,'naif','candu duniawi'),
	 (17033,'unknown','bertahanlah sedikit lebih lama'),
	 (1786,'sherina','singing pixie'),
	 (5630,'unknown','home');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (8567,'puti chitara','the sweet nightmare'),
	 (13889,'zeke khaseli','enter the spider'),
	 (6872,'unknown','untung ada kamu'),
	 (5936,'unknown','naradira'),
	 (11668,'ady','cinta tak berarah'),
	 (2612,'andre harihandoyo & sonic people','who took my money'),
	 (10888,'unknown','ikhtisar'),
	 (4077,'unknown','selalu cinta'),
	 (14486,'unknown','pretty lies'),
	 (3049,'unknown','biar sa yang mengalah');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (1760,'setia','sakit hati'),
	 (6726,'wideks','tak seindah harap'),
	 (818,'raisa','love you longer'),
	 (18109,'element','tak tersisa'),
	 (8686,'dhanis martin','kusematkan cintaku'),
	 (1639,'naff','kuingin kau selalu ada'),
	 (1596,'maudy ayunda','i am more'),
	 (2796,'marion jola','damba'),
	 (1836,'st12','pangeran cinta'),
	 (15201,'benyamin s','ngupi');
INSERT INTO demo_music.m_songs (code,original_artist,song_title) VALUES
	 (6771,'unknown','gak ada manggungnya'),
	 (6629,'om pmr (pengantar minum racun)','inagurasi'),
	 (2681,'unknown','kenakalan remaja di era informatika'),
	 (8339,'unknown','before its too late'),
	 (12370,'sound da'' clan','cinta'),
	 (2044,'koes bersaudara','hanya kepadaku'),
	 (17225,'unknown','hukum dalam negeri'),
	 (15399,'connect worship,bobby febian,gracia thomas','cinta sempurna'),
	 (9658,'unknown','toki-toki (buaya)');
